const sharedReferenceImage = "/imgs/testimonials/johnson-screens.png";
const standardDescription =
  "Live, commissioned installation with documented performance data and ongoing operations support.";

export const testimonialShowcase = [
  {
    id: "wide-angle-2017",
    title: "Wide Angle",
    tag: "Industrial Solar",
    subtitle: "Client Reference",
    capacity: "120 kWp",
    installed: "2017",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-1.png",
  },
  {
    id: "loyal-equipments-2017",
    title: "Loyal Equipments Ltd",
    tag: "Industrial Solar",
    subtitle: "Client Reference",
    capacity: "120 kWp",
    installed: "2017",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-2.png",
  },
  {
    id: "otsuka-pharmaceutical-2018",
    title: "Otsuka Pharmaceutical India Pvt. Ltd.",
    tag: "Pharma",
    subtitle: "Client Reference",
    capacity: "2024 kWp",
    installed: "2018",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-3.png",
  },
  {
    id: "bharat-beams-2018",
    title: "Bharat Beams Pvt Ltd",
    tag: "Industrial Solar",
    subtitle: "Client Reference",
    capacity: "122 kWp",
    installed: "2018",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-4.png",
  },
  {
    id: "busch-vacuum-2020",
    title: "Busch Vacuum India Private Limited",
    tag: "Engineering",
    subtitle: "Client Reference",
    capacity: "72 kWp",
    installed: "2020",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-5.png",
  },
  {
    id: "swiss-pharma-2021",
    title: "Swiss Pharma Pvt Ltd",
    tag: "Pharma",
    subtitle: "Client Reference",
    capacity: "200 kWp",
    installed: "2021",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-6.png",
  },
  {
    id: "aqseptence-group-2021",
    title: "Aqseptence Group India Pvt Ltd",
    tag: "Water Tech",
    subtitle: "Client Reference",
    capacity: "150 kWp",
    installed: "2021",
    description: standardDescription,
    image: sharedReferenceImage,
  },
  {
    id: "somany-evergreen-2022",
    title: "Somany Evergreen Knits Ltd",
    tag: "Manufacturing",
    subtitle: "Client Reference",
    capacity: "900 kWp",
    installed: "2022",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-8.png",
  },
  {
    id: "raviraj-foils-2022",
    title: "Raviraj Foils Ltd",
    tag: "Manufacturing",
    subtitle: "Client Reference",
    capacity: "2100 kWp",
    installed: "2022",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-9.png",
  },
  {
    id: "siemens-energy-2023",
    title: "Siemens Energy",
    tag: "Engineering",
    subtitle: "Client Reference",
    capacity: "1300 kWp",
    installed: "2023",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-10.png",
  },
  {
    id: "johnson-screens-2023",
    title: "Johnson Screens",
    tag: "Industrial Solar",
    subtitle: "Client Reference",
    capacity: "170 kWp",
    installed: "2023",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-11.png",
  },
  {
    id: "honda-motorcycle-2023",
    title: "Honda Motorcycle & Scooter India Pvt. Ltd",
    tag: "Automotive",
    subtitle: "Client Reference",
    capacity: "2500 kWp",
    installed: "2023",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-12.png",
  },
  {
    id: "baxter-pharmaceuticals-2024",
    title: "Baxter Pharmaceuticals India Private Ltd",
    tag: "Pharma",
    subtitle: "Client Reference",
    capacity: "1300 kWp",
    installed: "2024",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-13.png",
  },
  {
    id: "loyal-equipments-2024",
    title: "Loyal Equipments Ltd",
    tag: "Industrial Solar",
    subtitle: "Client Reference",
    capacity: "250 kWp",
    installed: "2024",
    description: standardDescription,
    image: sharedReferenceImage,
  },
  {
    id: "fuji-silvertech-2024",
    title: "Fuji Silvertech",
    tag: "Manufacturing",
    subtitle: "Client Reference",
    capacity: "525.8 kWp",
    installed: "2024",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-15.png",
  },
  {
    id: "colgate-palmolive-2025",
    title: "Colgate Palmolive India Ltd",
    tag: "FMCG",
    subtitle: "Client Reference",
    capacity: "250 kWp",
    installed: "2025",
    description: standardDescription,
    image: "/imgs/testimonials/testimonial-16.png",
  },
];

export const testimonialReferenceImage = sharedReferenceImage;
