/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    clients: Client;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'services-header': ServicesHeader;
    'operations-maintenance-page': OperationsMaintenancePage;
    'contact-page': ContactPage;
    footer: Footer;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'services-header': ServicesHeaderSelect<false> | ServicesHeaderSelect<true>;
    'operations-maintenance-page': OperationsMaintenancePageSelect<false> | OperationsMaintenancePageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  status: 'published' | 'draft';
  /**
   * Lower numbers appear first on the Projects page.
   */
  sortOrder: number;
  name: string;
  /**
   * URL key used by case study links, for example honda-india.
   */
  slug: string;
  industry: string;
  year: string;
  capacity: string;
  plantType?: string | null;
  description: string;
  /**
   * Keeps compatibility with the existing frontend fallback structure.
   */
  meta?: string | null;
  companyIcon: number | Media;
  companyIconAlt?: string | null;
  image: number | Media;
  /**
   * Optional. If empty, the case study cover image can be used as the listing cover.
   */
  listingImage?: (number | null) | Media;
  hideListingCover?: boolean | null;
  hideListingLogo?: boolean | null;
  /**
   * Add, remove, and reorder the images shown inside the project case study.
   */
  galleryImages?:
    | {
        image: number | Media;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * Set this to 7 to place the logo at position 7. Other logos shift automatically.
   */
  sortOrder: number;
  name: string;
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  status: 'published' | 'draft';
  /**
   * Set this to 7 to place the testimonial at position 7. Others shift automatically.
   */
  sortOrder: number;
  title: string;
  tag: string;
  subtitle?: string | null;
  capacity?: string | null;
  installed?: string | null;
  description?: string | null;
  coverImage: number | Media;
  /**
   * Upload the company-specific PDF or another file opened when this card is clicked.
   */
  certificateFile: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  status?: T;
  sortOrder?: T;
  name?: T;
  slug?: T;
  industry?: T;
  year?: T;
  capacity?: T;
  plantType?: T;
  description?: T;
  meta?: T;
  companyIcon?: T;
  companyIconAlt?: T;
  image?: T;
  listingImage?: T;
  hideListingCover?: T;
  hideListingLogo?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  sortOrder?: T;
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  status?: T;
  sortOrder?: T;
  title?: T;
  tag?: T;
  subtitle?: T;
  capacity?: T;
  installed?: T;
  description?: T;
  coverImage?: T;
  certificateFile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  title: string;
  subtitle: string;
  eyebrow?: string | null;
  description: string;
  /**
   * Add, remove, reorder, and edit the three hero calls to action.
   */
  heroCtas?:
    | {
        label: string;
        href: string;
        /**
         * Material Symbols icon name, for example arrow_forward.
         */
        icon?: string | null;
        style: 'primary' | 'secondary' | 'green';
        id?: string | null;
      }[]
    | null;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  heroImage?: (number | null) | Media;
  heroImageMobile?: (number | null) | Media;
  heroVideo?: (number | null) | Media;
  aboutTitle: string;
  aboutBody: string;
  aboutImage?: (number | null) | Media;
  certifications?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  impactTitle: string;
  impactCards?:
    | {
        /**
         * Material Symbols icon name used by the frontend.
         */
        icon?: string | null;
        value: string;
        label: string;
        sublabel?: string | null;
        id?: string | null;
      }[]
    | null;
  videosTitle: string;
  videosIntro?: string | null;
  featuredVideos?:
    | {
        kind: 'youtube' | 'external' | 'upload' | 'placeholder';
        title: string;
        description?: string | null;
        /**
         * Paste a YouTube watch, share, or embed URL.
         */
        youtubeUrl?: string | null;
        externalUrl?: string | null;
        uploadedVideo?: (number | null) | Media;
        thumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  servicesTitle: string;
  services?:
    | {
        title: string;
        description: string;
        href: string;
        image?: (number | null) | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-header".
 */
export interface ServicesHeader {
  id: number;
  /**
   * Only controls the image shown when hovering each Services item in the header.
   */
  items?:
    | {
        title: string;
        image?: (number | null) | Media;
        imageAlt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operations-maintenance-page".
 */
export interface OperationsMaintenancePage {
  id: number;
  galleryCtaLabel: string;
  /**
   * These are the images shown on the Solar O&M gallery page.
   */
  galleryItems?:
    | {
        title: string;
        description?: string | null;
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  ctaCards?:
    | {
        eyebrow: string;
        title: string;
        action: string;
        href: string;
        external?: boolean | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  inquiryForm: {
    title: string;
    subtitle?: string | null;
    serviceOptions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Controls labels/placeholders for the main form fields.
     */
    fields?:
      | {
          key: string;
          label: string;
          placeholder?: string | null;
          type?: string | null;
          required?: boolean | null;
          id?: string | null;
        }[]
      | null;
    submitLabel?: string | null;
    successMessage?: string | null;
  };
  facility: {
    badge?: string | null;
    officeTitle?: string | null;
    companyName?: string | null;
    address: string;
    hours?: string | null;
    mapTitle?: string | null;
    mapDescription?: string | null;
    /**
     * Only this destination controls the Google Maps query.
     */
    mapDestination?: string | null;
  };
  urgentInquiry: {
    title?: string | null;
    description?: string | null;
    phoneLabel?: string | null;
    phone: string;
    emailLabel?: string | null;
    email: string;
  };
  phone: string;
  email: string;
  address: string;
  linkedin?: string | null;
  socials?:
    | {
        platform: string;
        handle?: string | null;
        url: string;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  description?: string | null;
  year?: string | null;
  services?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  quickLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  bottomWords?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  eyebrow?: T;
  description?: T;
  heroCtas?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        style?: T;
        id?: T;
      };
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  heroImage?: T;
  heroImageMobile?: T;
  heroVideo?: T;
  aboutTitle?: T;
  aboutBody?: T;
  aboutImage?: T;
  certifications?:
    | T
    | {
        label?: T;
        id?: T;
      };
  impactTitle?: T;
  impactCards?:
    | T
    | {
        icon?: T;
        value?: T;
        label?: T;
        sublabel?: T;
        id?: T;
      };
  videosTitle?: T;
  videosIntro?: T;
  featuredVideos?:
    | T
    | {
        kind?: T;
        title?: T;
        description?: T;
        youtubeUrl?: T;
        externalUrl?: T;
        uploadedVideo?: T;
        thumbnail?: T;
        id?: T;
      };
  servicesTitle?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        image?: T;
        alt?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-header_select".
 */
export interface ServicesHeaderSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        image?: T;
        imageAlt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operations-maintenance-page_select".
 */
export interface OperationsMaintenancePageSelect<T extends boolean = true> {
  galleryCtaLabel?: T;
  galleryItems?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  ctaCards?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        action?: T;
        href?: T;
        external?: T;
        icon?: T;
        id?: T;
      };
  inquiryForm?:
    | T
    | {
        title?: T;
        subtitle?: T;
        serviceOptions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        fields?:
          | T
          | {
              key?: T;
              label?: T;
              placeholder?: T;
              type?: T;
              required?: T;
              id?: T;
            };
        submitLabel?: T;
        successMessage?: T;
      };
  facility?:
    | T
    | {
        badge?: T;
        officeTitle?: T;
        companyName?: T;
        address?: T;
        hours?: T;
        mapTitle?: T;
        mapDescription?: T;
        mapDestination?: T;
      };
  urgentInquiry?:
    | T
    | {
        title?: T;
        description?: T;
        phoneLabel?: T;
        phone?: T;
        emailLabel?: T;
        email?: T;
      };
  phone?: T;
  email?: T;
  address?: T;
  linkedin?: T;
  socials?:
    | T
    | {
        platform?: T;
        handle?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  year?: T;
  services?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  quickLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  bottomWords?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}